version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nextjs-dashboard-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dashboard_user
      POSTGRES_PASSWORD: dashboard_password
      POSTGRES_DB: dashboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashboard_user -d dashboard_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
